enum ROUTES_NAMED {
  BOTTOM_TABS = 'BOTTOM_TABS',
  CATEGORIES = 'CATEGORIES',
  MEAL_OVERVIEW = 'MEAL_OVERVIEW',
  MEAL_DETAIL = 'MEAL_DETAIL',
  FAVORITE = 'FAVORITE',
}

export default ROUTES_NAMED